# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bird Call Review
email: 
description: Bird calls are incredibly diverse. But are they all good? Are some just okay? Can a bird call be sexy? Let's find out.
baseurl: ""
url: "http://birdcallreview.com"
twitter_username: birdcallreview

permalink: /:title

# Build settings
markdown: kramdown
